{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    kubernetes.io/metadata.name: {{ .Release.Namespace }}
    app.kubernetes.io/part-of: events-concierge
    {{- with .Values.namespace.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
