{{- if .Values.secretManager.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "events-concierge.runtimeSecretProviderClass" . }}
  labels:
    {{- include "events-concierge.labels" (dict "root" . "component" "runtime-secrets") | nindent 4 }}
spec:
  provider: gke
  parameters:
    secrets: |
      {{- range .Values.secretManager.runtimeSecrets }}
      - resourceName: "projects/{{ $.Values.secretManager.projectId }}/secrets/{{ .secretName }}/versions/{{ .version }}"
        path: {{ .fileName | quote }}
      {{- end }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "events-concierge.migrationSecretProviderClass" . }}
  labels:
    {{- include "events-concierge.labels" (dict "root" . "component" "migration-secrets") | nindent 4 }}
spec:
  provider: gke
  parameters:
    secrets: |
      {{- range .Values.secretManager.migrationSecrets }}
      - resourceName: "projects/{{ $.Values.secretManager.projectId }}/secrets/{{ .secretName }}/versions/{{ .version }}"
        path: {{ .fileName | quote }}
      {{- end }}
{{- end }}
