{{- $root := . -}}
{{- range $key, $account := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $account.name }}
  labels:
    {{- include "events-concierge.labels" (dict "root" $root "component" $key) | nindent 4 }}
  {{- if $account.gcpServiceAccount }}
  annotations:
    iam.gke.io/gcp-service-account: {{ $account.gcpServiceAccount | quote }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
