export const meta = {
  name: 'ec-adr-log',
  description: 'Write the events-concierge ADR log (11 ADRs seeded from judge verdicts) + cross-checking indexer',
  phases: [
    { title: 'Write', detail: 'one writer per ADR' },
    { title: 'Index', detail: 'cross-check numbers + README.md' },
  ],
}

const WS = '/Users/iliazlobin/Claude/events-concierge'
const DOC = WS + '/design/system-design.md'
const REQ = WS + '/design/requirements.md'
const P = { 1: WS + '/design/panels/01-discovery-topology.md', 2: WS + '/design/panels/02-registration-orchestration.md', 3: WS + '/design/panels/03-credential-isolation.md', 4: WS + '/design/panels/04-handoff-lifecycle.md' }

const ADRS = [
  { n: '001', slug: 'single-postgres-catalog', title: 'Single-Postgres catalog with versioned-replay ingest and tenant-overlay serving', seeds: [P[1]], scope: 'One Postgres 16 cluster as store of record AND serving index (raw landing + tenant-neutral canonical catalog with pgvector/tsvector/trigram + RLS tenant tables); batch micro-cycle ingestion via Temporal Schedules; ingest-time dedup for the shared catalog, query-time only for the per-user overlay, one pinned match library; append-only canonical_alias chain + single alias-resolver library; normalizer_version/merge_version stamps + raw retention + shadow re-merge; NO promotion of per-user-fetched Meetup events to the shared catalog at launch. Rejected: query-time federation (14-day horizon breaks NFR-1, SerpApi variance on hot path, weakest NFR-7 posture); staged 4-schema pipeline (over-tooled at 150-500k rows); any second search store.', riders: 'Per-user Meetup promotion deferred pending adversarial visibility fixture + Meetup ToS review; pgvector re-benchmark before assuming >5M rows safe.' },
  { n: '002', slug: 'tm-crawl-plan-budget-ledger', title: 'Ticketmaster crawl plan and budget governance (resolves O-8)', seeds: [P[1]], scope: '25 metros x 5 segments x 2 date windows {0-14d, 15-90d}, both at 6h cadence (5h30m schedule + <=15min lag => publication-to-discoverable <=6h); ~500 calls/cycle x 4 = ~2,000/day typical, soft cap 4,500, 500-call reserve for re-polls/splits/retries; BudgetLedger decrement strictly precedes dispatch; adapter makes size*page>=1000 and >5rps requests unconstructible; recursive cell split by genre then date-bisection, never deep-paging; degrade ladder sheds the 15-90d window first (12h => ~81 metros, 24h => ~105), never the 0-14d window; SerpApi sweeper 400 searches/day (~$150/mo plan).', riders: 'OWNER RATIFY: 25-metro launch grid (no signed decision pins a count); the far-window-freshness degrade ladder as explicit product posture; SerpApi spend; apply for the discretionary TM quota raise early (only escape past ~105 metros); build-time probe must validate the ~2-pages-per-cell assumption.' },
  { n: '003', slug: 'two-tier-orchestration', title: 'Two-tier Temporal orchestration: parent EventRequest workflow + per-(user,event) child sagas', seeds: [P[2]], scope: 'Parent workflowId req:{tenant}:{request_id} owns parse->discover->rank->conflict-gate + the FR-5.0 <=3-attempt loop; child workflowId {user}:{canonical_event_id} (REJECT_DUPLICATE, ParentClosePolicy=ABANDON) owns the FR-8.1 saga, within-candidate lane ladder, confirmation/handoff durable waits, months-long lifecycle; directive-signal protocol (outcome signal -> 10-min directive wait -> close | demote-to-handoff); intake start-outbox so an engine blip never loses a request; idempotency keys minted once in child workflow state; claim-check codec >256KB; lane ladder = within-candidate, attempts = per-candidate. Rejected: thin-workflow-fat-services (hand-rolled crash-critical attempt state; immaterial savings); event-driven choreography (closes workflow at non-terminal scheduled, net-new broker ops); one flat workflow (violates FR-8.1 granularity).', riders: 'OWNER RATIFY: FR-8.2 interpretation (discover/rank/select run as journaled activities in the PARENT since the child workflowId cannot exist before discovery mints canonical_event_id - the ADR records this as the closest achievable reading); re-request-after-failed default = handoff task (alternative ALLOW_DUPLICATE_FAILED_ONLY needs explicit sign-off); confirmation timeout 24h; directive wait 10 min.' },
  { n: '004', slug: 'data-plane-policy-killswitch', title: 'Data-plane policy enforcement: pre-mutate guard as the kill-switch mechanism', seeds: [P[2]], scope: 'Postgres-backed policy store (automation_allowed per source x modality, per-user limits, paid_allowed, kill_switch global+per-user) read through an in-process deterministic PDP with LISTEN/NOTIFY push (<=2s propagation); three layers: parent pre-skip, policy_gate activity, and THE mechanism - a deterministic non-LLM pre-mutate guard as the first instruction of every mutating activity re-reading policy immediately before the wire call (a Temporal signal cannot stop a dispatched activity); evaluation error or store outage = DENY, fail closed to handoff; kill-switch freeze-then-handoff semantics (park, 60s re-check, 30-min grace, then handoff). Rejected: OPA-sidecar fleet + batch-signal fan-out (signals cannot carry AC-50).', riders: 'OWNER RATIFY: kill-switch grace window 30 min.' },
  { n: '005', slug: 'redis-fair-share-pacer', title: 'Off-engine Redis fair-share pacer with the Meetup per-app quota contingency', seeds: [P[2]], scope: 'Redis token buckets keyed (source, credential): meetup:{user_token} 500pts/60s, luma:{calendar} 100 POST/5min with 429 full-block honor, tm:{app_key} 5rps+5,000/day (crawler); deficit-round-robin fair share; mutating + per-user-discovery activities acquire a lease pre-call; long projected waits convert to durable-timer backoff, not held workers; browser-pool admission cap lives here; Redis loss re-initializes buckets EMPTY (throttle-first). G2 contingency = config flip quota_scope[meetup]=app -> ONE global bucket + per-user FIFO lanes + DEGRADE-to-handoff past 5-min projected wait, autonomous-Meetup SLA flips to none. Rejected: Temporal-native quota entity workflows (engine round-trip per source call; pacing is politeness, not correctness).', riders: 'OWNER RATIFY: 5-min DEGRADE threshold. G2 spike remains DESIGN-BLOCKING for any autonomous-lane SLA number: must measure real consumedPoints per RSVP chain (the ~15pts figure is an unpublished estimate) and per-token vs per-app scoping.' },
  { n: '006', slug: 'managed-fleet-sovereign-trust-plane', title: 'Managed browser fleet (Browserbase) under a first-party sovereign trust plane', seeds: [P[3]], scope: 'Every secret-touching primitive first-party: siloed vault (per-tenant DEK, {tenant_id, credential_type} KMS encryption context via IAM condition keys; vault role can Encrypt but NOT Decrypt); injection broker = the ONLY kms:Decrypt principal (CI-asserted), fixed fill order pin-BEFORE-decrypt (live CDP origin check precedes any KMS call) -> mlock buffer -> Playwright fill -> zeroize on every exit; default-deny egress proxy, per-session allowlist, sticky identity = consistent-hash(tenant, source) egress-IP slot + fingerprint template, hashed at cookie capture and re-verified pre-reuse; session-start egress canary (fail-closed); deterministic action gate (closed grammar, submit only after fresh NOT_PRESENT detect, price==0 guard); CaMeL Reader/Planner split (Planner input schema has no raw-text field, CI-asserted); OTP as consumed-once KMS-encrypted claim-check ref in Temporal signals. Vendor supplies only per-(user,event) ephemeral Firecracker microVMs (Developer tier ~13 concurrent at launch -> Scale 250+), nothing persisted vendor-side; Fleet Port + tripwire at sustained 70 concurrent opens both the Scale contract motion and the gVisor self-host readiness spike (named migration target = Panel 3 gVisor design on standard EC2). Rejected: self-hosted Firecracker day one (breaches the $0.40 browser-lane bound at launch scale; breakeven ~5,000 concurrent = 37x the 100k design point); minimal-TCB gVisor self-host day one (same day-one fleet ownership; retained as migration design).', riders: 'OWNER RATIFY: AC-13 kernel-separation half verified by vendor attestation + behavioral tests until self-host migration (the one explicit binding-constraint exception); fill-time plaintext transit through the vendor CDP gateway as an accepted launch trade; tripwire value 70; AC-13 "kernel" interpretation (gVisor userspace kernel vs runsc -platform=kvm at ~2x host cost); Browserbase Scale contract checklist before ~75k users; Anthropic computer-use injection-classifier opt-out (replaced by the CaMeL split + deterministic gates).' },
  { n: '007', slug: 'db-anchored-lifecycle', title: 'DB-anchored lifecycle state machine with Temporal as the durable executor', seeds: [P[4]], scope: 'Postgres lifecycle table under FORCE RLS, partial unique index = one non-terminal row per (tenant, event); every transition through one guarded fn_transition committing state change + transition-ledger row (UNIQUE transition_id => retry no-op; ledger checked BEFORE the guarded update) + outbox row in ONE transaction; Temporal child workflow is the sole transition driver - mints transition_ids, owns all durable timers (TTL min(7d, event start), reminders T+24h/T+5d, confirmation 24h), receives all signals, ends in exactly one terminal state that releases resources; erasure = row-level crypto-shred (histories carry only claim-check keys); 15-min sweeper repairs orphans through the same function (safety net with divergence metric, never an authority); nightly invariant query. Rejected: workflow-state-as-SoT (immutable histories cannot satisfy 72h erasure or outbox atomicity; ~96M actions/mo of per-workflow polls); event-sourced log-as-SoT (standing discipline tax; benefits already provided by audit log + outbox + backups).', riders: 'OWNER RATIFY: conflict-at-completion semantics (warning surfaced AND lifecycle still advances + calendar written - if conflict should BLOCK the write it is a one-activity change, settle now); reopen-after-terminal = attempt-suffixed workflowIds {user}:{event}:r{n}; handoff TTL 7d capped at event start + reminder cadence (O-9 knobs).' },
  { n: '008', slug: 'central-change-detection', title: 'Central organizer-change detection keyed by distinct watched events (reconciles the Panel 1 / Panel 4 conflict)', seeds: [P[1], P[4]], scope: 'Watch registry of distinct (canonical_event_id, source) pairs derived from registered/scheduled lifecycle rows; per-source feeders: TM = catalog-crawl delta PLUS the full-population by-id re-poll of EVERY watched TM event every 6h from the 500-call reserve (Panel 1 canonical - the only variant under which NFR-17 survives the ADR-002 degrade ladder; Panel 4 <48h refinement survives as priority order within the reserve, not a cap - MUST record this reconciliation explicitly, see the post-panel note in the panel 4 file); Meetup = 3h poller, ONE status query per distinct watched event round-robin on watchers own tokens via the pacer, degrading to public JSON-LD on consumer revocation; Luma + handoff-lane = 3h public JSON-LD poll at human cadence + RelayInbox change-emails; event_change table with UNIQUE dedup fingerprint; fanout worker signals affected workflows; per-(source,event) staleness gauges alarm at the 6h bound. Rejected: per-workflow poll timers (N-watcher fetch multiplication, ~96M engine actions/mo).', riders: 'OWNER RATIFY: 3h poll cadence; TM re-poll reserve sizing (500 calls/day = ~125 concurrently watched TM events at 6h; overflow prioritizes soonest-starting + alerts + falls back to crawl delta) - confirm after G1 lands; Meetup ~5pts/status-query is an ASSUMPTION the G2 spike must measure (per-app worst case at 100k users could exceed the ceiling -> per-token sharding / adaptive cadence / coverage-loss alerting).' },
  { n: '009', slug: 'email-launch-notification-channel', title: 'Email to the real address as the launch notification channel; SMS stubbed behind the port', seeds: [P[4]], scope: 'SES v2 from notify.<domain> (distinct identity from the RelayInbox u.<domain>; CI lint forbids outbound from the relay domain); outbox consumer with LISTEN/NOTIFY wake + SKIP LOCKED claims; notification ledger UNIQUE dedup key = at-most-once user-visible; bounded retry 5 attempts over ~43min then failed+alert; hard bounce -> suppression + ops escalation; NFR-2(b) measured at the SES delivery event; alert thresholds 45s task-available / 90s user-notified; signed one-tap mark-done URL in every notification; Reply-To act+<token>@in.<domain> for un-RSVP/DONE; sending-domain warm-up overlaps the Google sensitive-scope verification wait. Rejected: SMS first (A2P 10DLC weeks of lead time for zero launch need); Twilio adapter ships as a stub with a channel-swap runbook.', riders: 'OWNER RATIFY: email-only launch consequence (a hard-bouncing address can reach TTL expiry without effective notice; mitigation = onboarding address verification + bounce alerting); the SES-delivery-event measurement boundary (recipient-MTA greylisting can push p99 past 120s and is outside our control); fuzzy completion never auto-completes (one extra tap vs zero wrong-task advances).' },
  { n: '010', slug: 'temporal-cloud-engine', title: 'Temporal Cloud as the durable-execution engine (DBOS documented fallback) - sizing and outage posture', seeds: [P[2]], scope: 'Settled in requirements FR-8.1 (this ADR ratifies and parameterizes, per O-6): one durable workflow per (user_id, canonical_event_id), workflowId idempotency with reject-duplicate; load basis 750 req/min peak -> ~390 child starts/min, worst-case ~1,600 engine transitions/s vs engine ceilings in the tens of thousands; ~240k open lifecycle children consume zero worker resources in durable waits; claim-check for >2MB payloads; the two-tier shape ports to DBOS (parent+child become two workflow functions) if O-6 contract review fails. Outage posture: intake start-outbox buffers request starts; in-flight state resumes losslessly; NO new handoff task can be created during an engine outage - a bounded NFR-2/NFR-15 exception accepted over building a second non-Temporal handoff path.', riders: 'OWNER RATIFY: the outage posture (bounded handoff-creation gap during an engine outage); O-6 contract checks - Temporal Cloud SLA >= 99.9% and namespace throughput >= ~1,600 transitions/s peak and the ~$25/M-actions cost basis are external figures NOT dossier-backed, verify at contract before treating parent action volume as immaterial.' },
  { n: '011', slug: 'relay-inbox-no-gmail', title: 'Per-user RelayInbox for login codes and confirmations; permanent no-Gmail rule', seeds: [P[3], P[4]], scope: 'Settled in research (d16) and requirements (FR-1.5, FR-5.7/5.8); this ADR ratifies the architecture: per-user alice@u.<domain> provisioned at onboarding; SES inbound -> per-tenant KMS-encrypted S3 prefix -> deterministic Lambda extraction (sender-domain allowlist, HTML strip, no LLM ever sees raw email) -> OTP/confirmation as consumed-once KMS-encrypted claim-check refs signaled to workflows; RelayInbox is structurally inbound-only; magic-link/OTP treated as short-TTL secrets; email treated as an untrusted indirect-injection vector. Keeps the Google surface calendar-only: sensitive-scope verification (3-6 weeks, pre-launch critical path) instead of restricted-scope CASA. Rejected: Gmail read scope (restricted scope, CASA assessment, permanent no-Gmail rule; blast radius).', riders: 'GATE G3 (pre-design verification, still open): do Luma/Eventbrite/Meetup signup validators ACCEPT relay addresses? If rejected -> reputable dedicated domain / per-user real mailbox / first-login handoff fallbacks; gates FR-2.13 account linking. Handoff users registering with their REAL email silence the confirmation-match and change-email channels for that event (poll-only flag).' },
]

function adrPrompt(a) {
  return [
    'Write the file ' + WS + '/decisions/adr-' + a.n + '-' + a.slug + '.md — one Architecture Decision Record for the Events Concierge system. Read first: the authoritative judge-panel verdict file(s) ' + a.seeds.join(' and ') + ' (the Decision/Rationale/Decided mechanism/Rejected alternatives/Edge cases/Owner ratification sections are your primary source — EXPAND from them, do not invent), plus the design doc ' + DOC + ' (sections that touch this decision) and the requirements ' + REQ + ' (cite FR/NFR/AC/gate numbers where they bind).',
    'FORMAT (exactly):',
    '# ADR-' + a.n + ': ' + a.title,
    '**Status:** accepted' + (a.riders ? ' — with owner-ratification riders (see Consequences)' : '') + ' · **Date:** 2026-07-10',
    '## Context — the forces: requirements, evidence, constraints. One tight paragraph + sharp bullets. Name the binding FR/NFR/AC/gate numbers.',
    '## Options considered — numbered; each option one paragraph including the REAL rejection reason from the verdict (no straw men).',
    '## Decision — active voice ("We will …"), concrete: mechanisms, invariants, launch parameters with their numbers.',
    '## Consequences — what becomes easier AND harder; risks accepted; follow-ups committed; an explicit "Owner-ratification riders" bullet list at the end covering: ' + (a.riders || 'none') + '.',
    'DECISION SCOPE (what this ADR covers): ' + a.scope,
    'Style: dense, complete sentences, no emoji, no filler, no provenance language about panels/agents/workflows in the body prose (the verdict files are inputs, not citations — EXCEPTION: ADR-008 must explicitly record the panel-conflict reconciliation described in its scope). Keep it to roughly 60-110 lines. Return only the file path when written.',
  ].join('\n\n')
}

const indexPrompt = [
  'You are the ADR indexer + consistency checker for the Events Concierge decisions log. Read every ADR in ' + WS + '/decisions/ (adr-001 … adr-011), plus ' + DOC + ' and ' + REQ + '.',
  'Tasks:',
  '1. Cross-check every NUMBER shared between an ADR and the design doc or requirements (quotas, cadences, TTLs, thresholds, attempt budgets, concurrency, costs, SLA targets). Where an ADR has trivial numeric drift from the design doc, FIX the ADR in place with Edit (the design doc + requirements are authoritative). Where a contradiction is judgment-bearing (not trivial), do NOT fix — report it.',
  '2. Write ' + WS + '/decisions/README.md: a heading, one-line purpose ("Immutable decision log for the Events Concierge system design; supersede, never edit"), then a markdown table: ADR | Title | Status | One-line decision | Owner-ratification riders (a terse comma-separated list, or "-"). After the table, a short "Open gates" section listing G1/G2/G3 and which ADRs they gate (G2 -> ADR-005/008, G3 -> ADR-011, G1 -> ADR-002/008 sizing confirmations).',
  '3. Return a short report: files indexed, numeric fixes applied (file + what), judgment-bearing contradictions found (should be none), riders count.',
].join('\n')

phase('Write')
const written = (await parallel(ADRS.map(a => () =>
  agent(adrPrompt(a), { label: 'adr-' + a.n, phase: 'Write', effort: 'medium' }).then(() => 'adr-' + a.n + '-' + a.slug + '.md')
))).filter(Boolean)
log('ADRs written: ' + written.length + '/11')

phase('Index')
const report = await agent(indexPrompt, { label: 'index+consistency', phase: 'Index', effort: 'high' })
return { written, report }